name: publish

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Test Pack and Publish
    steps:

      - name: Checkout
        uses: actions/checkout@v3
   
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

      - name: Build - Debug
        run: dotnet build src/Interprocess.sln

      - name: Test - Debug
        run: dotnet test --no-build --verbosity=detailed src/Interprocess.sln

      - name: Build - Release
        run: dotnet build -c Release src/Interprocess.sln

      - name: Pack
        run: dotnet pack -c Release --no-build --output . --version-suffix ${{github.run_number}} src/Interprocess/Interprocess.csproj 

      - name: Push
        run: dotnet nuget push Cloudtoid.Interprocess.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nuget_org_api_key }}